### PR TITLE
Support for alternative translations

### PR DESCRIPTION
**Pull request by koiuo**
Specifying -x option will show alternative translations. Implementation is a bit bulky, tried to keep it as small as possible. Let me know, if there are better ways to implement this.

### CODE REVIEW

**Comment by Narrat** [comment]
Wow, nice. Would close my #3 Will look into it.

One note so far; https://github.com/edio/translate/blob/master/translate#L14 This line got somehow cloned

**Comment by edio** [comment]
Fixed duplicated lines. Squashed commits. What else?
Don't hesitate to let me know of any issues, even if it requires reworking patch completely.

**Comment by Narrat** [comment]
Why not argparse or getopt to catch the -x option? Some special reasons despite introduction of a new import and doubtable gain with just one option?

**Comment by edio** [comment]
> introduction of a new import and doubtable gain with just one option

That's exactly that. But would eagerly add argparse if you agree it's necessary here

**Comment by Narrat** [comment]
It would look less like a hack and despite that I thought about using it to make the language idents optional, if possible (if it doesn't unresolvable break stdin, etc)

So in case I would favor it

**Comment by edio** [comment]
Done. Also gave more descriptive names to some vars.

**Comment by Narrat** [comment]
Looking good to me. Descriptive enough to get through what the parser is doing (even if someone hasn't touched such a thing before, like me)
Only way I could think of improving it, requires to know what type the response is and rely on modules that python offers. But dunno. It's not json, nor xml

Remaining stuff would be, to add a note in the man-page about the new option and move the options from argparse PEP8 conform so that some of the spaces can be removed. Really far off to the right :D

**Comment by edio** [comment]
Regarding response format. It is very similar to python source code. And in fact I tried evaluating response as python code, but it failed and I didn't want to investigate, because besides of that, evaluating something that comes from the net isn't safe at all.

What about PEP8? I don't understand.

Also, updated man page.

**Comment by Narrat** [comment]
Good point about safety.

https://www.python.org/dev/peps/pep-0008/ Style Guide. (Not that I'm that much into it either *cough*). But a good place to start

**Comment by edio** [comment]
I just don't understand what exactly you expect to see. Anyway, made lines shorter. Still conforms to PEP8 though.

**Comment by Narrat** [comment]
Like it is now. Before it was around ~30-45 whitespaces for one line at the parser var where I thought it's too much, especially if there are long sentences involved after that.

Well, all that remains now is merging, or did I forget something?

**Comment by edio** [comment]
If it looks good for you, then merge please :)

**Comment by Narrat** [comment]
Done :)

**Pull request merged**
